// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLprgPC-zr_aPgTHIVLzetgM17DwIJnLE',
    appId: '1:40708660719:web:0304803e00047d08c9aa1a',
    messagingSenderId: '40708660719',
    projectId: 'fir-ecommerce-3b775',
    authDomain: 'fir-ecommerce-3b775.firebaseapp.com',
    storageBucket: 'fir-ecommerce-3b775.firebasestorage.app',
    measurementId: 'G-QTQH3WNWDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkaSQwSrVxswExVsObAxsxTUJHdw7AJSU',
    appId: '1:40708660719:android:b021c2da68758f6cc9aa1a',
    messagingSenderId: '40708660719',
    projectId: 'fir-ecommerce-3b775',
    storageBucket: 'fir-ecommerce-3b775.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3HDdODu2wGPAyJH5jEOSf5XfOoCna9P0',
    appId: '1:40708660719:ios:acf40fd807f9add3c9aa1a',
    messagingSenderId: '40708660719',
    projectId: 'fir-ecommerce-3b775',
    storageBucket: 'fir-ecommerce-3b775.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );
}
